config/routes.rb
Rails.application.routes.draw do

  resources :comments
  devise_for :users
  resources :images
  root to: "home#index"

  get '/pictures', to: 'home#pictures', as: 'pictures'
  get '/photos', to: 'home#photos', as: 'photos'
  get '/emoticons', to: 'home#emoticons', as: 'emoticons'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(u)
    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)

    @user = u

    if @user.blank?
      roles_for_guest
    elsif @user.admin?
      roles_for_admin
    else
      roles_for_member
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end

  private

  def roles_for_guest
    can :read, Image    
  end

  def roles_for_member
    can :manage, Image, user_id: user.id

    can :read, Image
    can :create, Image
  end

  def roles_for_admin
    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :image

  scope :latest, -> { order(updated_at: :desc) }

  validates :content, presence: true, length: { minimum: 1 }
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :file

  belongs_to :user
  has_many :comments

  scope :eyes, -> { where(image_type: Image.image_types[:eye]) }
  scope :pictures, -> { where(image_type: Image.image_types[:picture]) }
  scope :photos, -> { where(image_type: Image.image_types[:photo]) }
  scope :emoticons, -> { where(image_type: Image.image_types[:emoticon]) }

  scope :latest, -> { order(updated_at: :desc) }

  enum image_types: { eye: 0, picture: 1, photo: 2, emoticon: 3 }

  validates :title, presence: true, length: { maximum: 20 }
  validates :image_type, presence: true, inclusion: { in: [0, 1, 2, 3]}
  validates :user_id, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  def image_thumb_url(process)
    self.file.service_url(params: { "x-oss-process" => process })
  end

  def room
    key
  end

  def up_hits
    $redis.hincrby(key, "hits", 1)
  end

  def hits
    $redis.hget(key, "hits").to_i
  end

  def key
    "#{self.class.name.downcase}_#{id}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :images
  has_many :comments

  # 是否是管理员
  def admin?
    "info@tuliang.org".freeze == email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_back(fallback_location: root_path, alert: '您无权访问此页面。'.freeze)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to image_path(@comment.image_id), notice: '评论成功'.freeze }
        format.js { flash.now[:notice] = '评论成功'.freeze }
        format.json { render :show, status: :created, location: @comment }

        ActionCable.server.broadcast @comment.image.room, user: @comment.user, comment: @comment
      else
        format.html { redirect_to image_path(@comment.image_id), alert: '评论内容不能为空'.freeze }
        format.js { flash.now[:alert] = '评论内容不能为空'.freeze }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :image_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /
  def index
  	@images = Image.latest
  end

  # GET /pictures
  def pictures
    @images = Image.pictures.latest

    render :index
  end

  # GET /photos
  def photos
    @images = Image.photos.latest

    render :index
  end

  # GET /emoticons
  def emoticons
    @images = Image.emoticons.latest

    render :index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  layout "image", only: [:show]

  # GET /images
  # GET /images.json
  def index
    @images = current_user.images.latest

    render 'home/index'.freeze
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @comment = Comment.new
    @comments = @image.comments.latest

    @image.up_hits
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: '创建成功'.freeze }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: '更新成功'.freeze }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: '删除成功'.freeze }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find_by_id(params[:id])
    redirect_back(fallback_location: root_path, alert: '此页面不存在'.freeze) if @image.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def image_params
    params.require(:image).permit(:title, :image_type, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def file_url_helper(image, thumb = false)
    return "image-#{Image.image_types.key(image.image_type)}.jpg" unless image.file.attached?

    if thumb
      image.image_thumb_url("image/resize,h_600")
    else
      image.file.service_url
    end
  end

  def flash_class_helper(level)
    case level
      when 'notice' then "alert alert-info alert-dismissible"
      when 'success' then "alert alert-success alert-dismissible"
      when 'error' then "alert alert-danger alert-dismissible"
      when 'alert' then "alert alert-warning alert-dismissible"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <%= form.hidden_field :image_id, value: image.id %>

  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-label-group">
    <% if user_signed_in? %>
      <%= form.text_area :content, class: "form-control" %>
    <% else %>
      <%= form.text_area :content, class: "form-control", disabled: "disabled" %>
    <% end %>
  </div>

  <% if user_signed_in? %>
    <%= form.submit "评论", class: "btn btn-primary btn-block" %>
  <% else %>
    <%= link_to "请登陆", new_user_session_path, class: "btn btn-primary btn-block" %>
  <% end %>
<% end %>

app/views/comments/create.js.erb
$("#flash").html("<%=j render 'layouts/flash' %>");
<% if @comment.persisted? %>
  $("#comment_content").val("");
  $("#comments").prepend("<%=j render 'images/comment', comment: @comment %>");  
  $("#comments .row:first .card").hide().fadeIn(1000);
<% end %>

app/views/home/_image.html.erb
<div class="col-md-3">
  <div class="card mb-3 box-shadow">
    <%= link_to image_path(image), target: "_blank" do %>
      <div class="card-img-top" style="background-image:url('<%= asset_path(file_url_helper(image, true)) %>');"></div>
    <% end %>
    
    <div class="card-body">
      <p class="card-title"><%= image.title %></p>
      <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted"><%= time_ago_in_words image.updated_at %>前更新</small>
        <% if user_signed_in? && controller_name == "images" %>
          <div class="btn-group">
            <%= link_to '修改', edit_image_path(image), class: "btn btn-sm btn-outline-secondary" %>
            <%= link_to '删除', image, method: :delete, data: { confirm: '确定删除?' }, class: "btn btn-sm btn-outline-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <%= render partial: 'home/image'.freeze, collection: @images %>
</div>

app/views/images/_comment.html.erb
<div class="row py-1">

    <div class="col-md-12">
      <div class="card mb-12 box-shadow">
        <div class="card-body">
          <p class="card-title">
            <%= comment.user.email %>
          </p>
          <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted"><%= time_ago_in_words comment.updated_at %>前更新</small>
          </div>
          <div class="card-img py-3">
            <%= comment.content %>
          </div>
        </div>
      </div>
    </div>

</div>

app/views/images/_form.html.erb
<%= form_with(model: image, local: true, html: { class: "form-signin py-5", multipart: true } ) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center mb-4">
    <h1 class="h3 mb-3 font-weight-normal"><%= title %></h1>
  </div>

  <div class="form-label-group">
    <%= form.label :title, "标题" %>
    <%= form.text_field :title, autofocus: true, required: true, placeholder: "标题", class: "form-control" %>
  </div>

  <div class="form-label-group">
    <%= form.label :image_type, "类型" %>
    <%= form.enum_select :image_type, {}, { required: true, placeholder: "类型", class: "custom-select" } %>
  </div>

  <div class="form-label-group">
    <div class="custom-file">
      <%= form.label :file, "选择图片", class: "custom-file-label" %>
      
      <% if image.file.attached? %>
        <%= form.file_field :file, direct_upload: true, class: "custom-file-input" %>
      <% else %>
        <%= form.file_field :file, required: true, direct_upload: true, class: "custom-file-input" %>
      <% end %>
    </div>
  </div>

  <% if image.file.attached? %>
    <div class="form-label-group">
      <%= image_tag image.file.service_url, class: "form-control" %>
    </div>
  <% end %>

  <%= form.submit "提交", class: "btn btn-primary btn-block" %>
<% end %>

app/views/images/edit.html.erb
<%= render 'form', image: @image, title: "修改图片" %>

app/views/images/new.html.erb
<%= render 'form', image: @image, title: "发布图片" %>

app/views/images/show.html.erb
<div class="row py-1">

    <div class="col-md-12">
      <div class="card mb-12 box-shadow">
        <div class="card-body">
          <p class="card-title"><%= @image.title %></p>
          <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted"><%= time_ago_in_words @image.updated_at %>前更新 浏览：<%= @image.hits %></small>
            <% if user_signed_in? && current_user.id == @image.user_id %>
              <div class="btn-group">
                <%= link_to '修改', edit_image_path(@image), class: "btn btn-sm btn-outline-secondary" %>
                <%= link_to '删除', @image, method: :delete, data: { confirm: '确定删除?' }, class: "btn btn-sm btn-outline-danger" %>
              </div>
            <% end %>
          </div>
          <div class="card-img py-3"><%= image_tag(file_url_helper(@image), class: "img-fluid") %></div>
        </div>
      </div>
    </div>

</div>

<div id="flash"></div>

<div class="row py-1">
    <div class="col-md-12">
      <div class="card mb-12 box-shadow">
        <div class="card-body">
          <div class="card-img py-3">
            <% if user_signed_in? %>
             <p><%= current_user.email %></p>
            <% end %>
            <%= render 'comments/form', comment: @comment, image: @image %>
          </div>
        </div>
      </div>
    </div>
</div>

<div id="comments" data-room="<%= @image.room %>">
  <%= render partial: 'images/comment'.freeze, collection: @comments %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class_helper(key) %> fade show" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>眼中</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-white border-bottom">
      <div class="container d-flex flex-column flex-md-row align-items-center p-3 px-md-4">
        <nav class="my-2 my-md-0 mr-md-3 mr-md-auto">
          <%= link_to '眼中（Beta)', root_path, class: "p-2 text-muted" %>
          <%= link_to '绘画', pictures_path, class: "p-2 text-muted" %>
          <%= link_to '照片', photos_path, class: "p-2 text-muted" %>
          <%= link_to '表情', emoticons_path, class: "p-2 text-muted" %>
        </nav>
 
        
        <nav class="my-2 my-md-0 mr-md-3">
          <% if user_signed_in? %>
            <%= link_to "管理", images_path, class: "p-2 text-muted" %>
            <%= link_to "发布", new_image_path, class: "p-2 text-muted" %>
          <% else %>
            <%= link_to "注册", new_registration_path(:user), class: "p-2 text-muted" %>
          <% end %>
        </nav>
        
        <% if user_signed_in? %>
          <%= link_to "退出", destroy_user_session_path, class: "btn btn-outline-danger", method: :delete, data: { confirm: '确定退出?' } %>
        <% else %>
          <%= link_to "登陆", new_user_session_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </header>

    <main role="main">
      <div class="py-5 bg-light">
        <div class="container">
          <% flash.each do |key, value| %>
            <div class="<%= flash_class_helper(key) %>">
              <%= value %>
            </div>
          <% end %>
    
          <%= yield %>
        </div>
      </div>
    </main>

    <footer class="text-muted">
      <div class="container pt-4 my-md-5 pt-md-5 border-top">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>本站在 <a href="https://github.com/tuliang/in-the-eyes" target="_blank" rel="nofollow" title="本站在 GitHub 上面的开源内容">GitHub</a> 上开源</p>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/image.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>眼中</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-white border-bottom">
      <div class="container d-flex flex-column flex-md-row align-items-center p-3 px-md-4">
        <nav class="my-2 my-md-0 mr-md-3 mr-md-auto">
          <%= link_to '眼中（Beta)', root_path, class: "p-2 text-muted" %>
          <%= link_to '绘画', pictures_path, class: "p-2 text-muted" %>
          <%= link_to '照片', photos_path, class: "p-2 text-muted" %>
          <%= link_to '表情', emoticons_path, class: "p-2 text-muted" %>
        </nav>
 
        
        <nav class="my-2 my-md-0 mr-md-3">
          <% if user_signed_in? %>
            <%= link_to "管理", images_path, class: "p-2 text-muted" %>
            <%= link_to "发布", new_image_path, class: "p-2 text-muted" %>
          <% else %>
            <%= link_to "注册", new_registration_path(:user), class: "p-2 text-muted" %>
          <% end %>
        </nav>
        
        <% if user_signed_in? %>
          <%= link_to "退出", destroy_user_session_path, class: "btn btn-outline-danger", method: :delete, data: { confirm: '确定退出?' } %>
        <% else %>
          <%= link_to "登陆", new_user_session_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </header>

    <main role="main">
      <div class="py-5 bg-light">
        <div class="container">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer class="text-muted">
      <div class="container pt-4 my-md-5 pt-md-5 border-top">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>本站在 <a href="https://github.com/tuliang/in-the-eyes" target="_blank" rel="nofollow" title="本站在 GitHub 上面的开源内容">GitHub</a> 上开源</p>
      </div>
    </footer>
  </body>
</html>